config/routes.rb
Market::Application.routes.draw do

  resources :images
  resources :items
  resources :shopkeepers
  resources :shops
  resources :users

end

app/models/etsy_listing.rb
# -*- coding: utf-8 -*-

class EtsyListing < ActiveRecord::Base

  belongs_to :item

  # Facade

  def url
    "http://www.etsy.com/listing/#{xid}/#{slug}"
  end

end

app/models/image.rb
# -*- coding: utf-8 -*-

class Image < ActiveRecord::Base

  def name
    name_in_en
  end

end

app/models/item.rb
# -*- coding: utf-8 -*-

class Item < ActiveRecord::Base

  belongs_to :shop
  has_many :shopkeepers, :through => :shop
  has_one :etsy_listing
  has_one :paypal_listing

  def name
    name_in_en
  end

  def description
    description_in_en
  end

  def price
    price_in_usd
  end

  def weight
    mass
  end

  def volume
    length * width * height
  end

  def tags
    []
  end

end

app/models/paypal_listing.rb
#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

class PayPalListing

  belongs_to :item

  def set(ops={})
    @hosted_button_xid = ops[:hosted_button_xid]
    @code = ops[:code]
    @description = ops[:description]
  end

  def fields
    [
     hosted_button_xid,
     code,
     description
    ]
  end

  def hosted_button_form
    if !hosted_button_xid then return nil end
    "<form class=\"buy\" action=\"https://www.paypal.com/cgi-bin/webscr\" method=\"post\"/>\n" \
    + "<input type=\"hidden\" name=\"cmd\" value=\"_s-xclick\"/>\n" \
    + "<input type=\"hidden\" name=\"hosted_button_id\" value=\"#{hosted_button_xid}\"/>\n" \
    + "<input class=\"buy\" type=\"submit\" value=\"Buy\"/>\n" \
    + "</form>"
  end

  def hosted_button_form_blank
    "<form>\n" \
    + "<input type=\"submit\" value=\"Unavailable\"\>\n" \
    + "</form>"
  end

end

app/models/shop.rb
#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

class Shop < ActiveRecord::Base

  has_many :shopkeepers
  has_many :users, :through => :shopkeepers

  def name
    name_in_en
  end

  def description
    description_in_en
  end
  
end

app/models/shopkeeper.rb
#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

class Shopkeeper < ActiveRecord::Base
  belongs_to :shop
  belongs_to :user
end

app/models/user.rb
#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

class User < ActiveRecord::Base

  has_many :shopkeepers
  has_many :shops, :through => :shopkeepers

  def name
    name_in_en
  end
  
  def description
    description_in_en
  end

end

app/controllers/application_controller.rb
# -*- coding: utf-8 -*-

class ApplicationController < ActionController::Base
  protect_from_forgery
  layout :layout_customizer

  private
  def layout_customizer
    @shop.key + '/application'
  end

  def layout_folder
    # To set the layout folder, we massage the request host 
    # into a shop key by doing these steps:
    #   - chop off the top level domain, e.g. ".com", ".net", etc.
    #   - chop off a leading "a." because we use this for our local testing.
    #
    # Examples:
    #   - a.foo.com => foo
    #   - www.foo.com => foo
    #   - abc.foo.com => abc.foo
    @shop = Shop.find_by_request_host(request.host())
  end

end

app/controllers/images_controller.rb
# -*- coding: utf-8 -*-

class ImagesController < InheritedResources::Base
end

app/controllers/items_controller.rb
# -*- coding: utf-8 -*-

class ItemsController < InheritedResources::Base
end

app/controllers/shopkeepers_controller.rb
# -*- coding: utf-8 -*-

class ShopkeepersController < InheritedResources::Base
end

app/controllers/shops_controller.rb
# -*- coding: utf-8 -*-

class ShopsController < InheritedResources::Base
end

app/controllers/users_controller.rb
# -*- coding: utf-8 -*-

class UsersController < InheritedResources::Base
end

app/helpers/application_helper.rb
# -*- coding: utf-8 -*-

module ApplicationHelper
end

app/helpers/begin_and_end_view_helper.rb
# -*- coding: utf-8 -*-

module BeginAndEndViewHelper

  # Begin a view page by providing a page-specific footer,
  # typically with a headline and/or links for REST actions.
  #
  # Called by:
  #   - begin_view_new
  #   - begin_view_edit
  #   - begin_view_index
  #   - begin_view_show
  #
  # Exampe:
  #   begin_view("foo","goo","hoo") 
  #   => "<h1>foogoohoo</h1>"

  def begin_view(*html_fragments)
    "<div id=\"begin_view\"><h1>#{html_fragments.join}</h1></div>\n\n".html_safe
  end


  # Begin a page that is view/*/edit.html.erb.
  # You may want to override this for your app.
  # This returns "<h1>Edit Object</h1>".

  def begin_view_edit(object_locale_key)
    begin_view(t(:Edit)," ",t(object_locale_key))
  end


  # Begin a page that is view/*/index.html.erb.
  # You may want to override this for your app.
  # This returns "<h1>List Objects</h1>".

  def begin_view_index(objects_locale_key)
    begin_view(t(objects_locale_key))
    #begin_view(t(:List)," ",t(objects_locale_key))
  end


  # Begin a page that is view/*/new.html.erb.
  # You may want to override this for your app.
  # This returns "<h1>Create Object</h1>".

  def begin_view_new(object_locale_key)
    begin_view(t(:Create)," ",t(object_locale_key))
  end


  # Begin a page that is view/*/show.html.erb
  # You may want to override this for your app.
  # This returns "<h1>Show Object</h1>".

  def begin_view_show(object_locale_key)
    begin_view(t(:Show)," ",t(object_locale_key))
  end


  # End a view page by providing a page-specific footer,
  # typically with navigation links for REST actions.
  #
  # Called by:
  #   - end_view_new
  #   - end_view_edit
  #   - end_view_index
  #   - end_view_show
  #
  # Exampe:
  #   end_view("foo","goo","hoo") 
  #   => "<div id="end">foogoohoo</div>>

  def end_view(*html_fragments)
    "<div id=\"end_view\">#{html_fragments.join}</div>\n".html_safe
  end


  # End a page that is view/*/edit.html.erb.
  # You may want to override this for your app.
  # This adds a link_to_back and link_to_show.

  def end_view_edit(objects_path=nil,object=nil)
    end_view(link_to_back(objects_path),link_to_show(object))
  end


  # End a page that is view/*/index.html.erb.
  # You may want to override this for your app.
  # This adds a link_to_create.

  def end_view_index(new_object_path=nil)
    end_view(link_to_create(new_object_path))
  end


  # End a page that is view/*/new.html.erb.
  # You may want to override this for your app.
  # This adds a link_to_back.

  def end_view_new(objects_path=nil)
    end_view(link_to_back(objects_path))
  end


  # End a page that is view/*/show.html.erb
  # You may want to override this for your app.
  # This adds a link_to_back and link_to_edit.

  def end_view_show(objects_path=nil, edit_object_path=nil)
    end_view(link_to_back(items_path)," ",link_to_edit(edit_object_path))
  end


end

app/helpers/images_helper.rb
# -*- coding: utf-8 -*-

module ImagesHelper
end

app/helpers/items_helper.rb
# -*- coding: utf-8 -*-

module ItemsHelper
end

app/helpers/shopkeepers_helper.rb
# -*- coding: utf-8 -*-

module ShopkeepersHelper
end

app/helpers/shops_helper.rb
# -*- coding: utf-8 -*-

module ShopsHelper
end

app/helpers/users_helper.rb
# -*- coding: utf-8 -*-

module UsersHelper
end

app/helpers/views_helper.rb
# -*- coding: utf-8 -*-                                                                                                           

module ViewsHelper

  H1_OPEN = "<h1>".html_safe
  H1_SHUT = "</h1>".html_safe
  H2_OPEN = "<h2>".html_safe
  H2_SHUT = "</h2>".html_safe
  H3_OPEN = "<h3>".html_safe
  H3_SHUT = "</h3>".html_safe

  def h1(sym)
    H1_OPEN + t(sym) + H1_SHUT
  end

  def h2(sym)
    H2_OPEN + t(sym) + H2_SHUT
  end

  def h3(sym)
    H3_OPEN + t(sym) + H3_SHUT
  end

  def icon(file_name_key,alt_text_key)
    "<img border=\"0\" width=\"16\" height=\"16\" src=\"/img/icons/silk/#{file_name_key}.png\" alt=\"#{t(alt_text_key)}\"/>".html_safe
  end

  def link_to_create(ops={})
    ops ? link_to(icon(:create, t(:Create)), ops) : ''
  end

  def link_to_back(ops={})
    ops ? link_to(icon(:back, t(:Back)), ops) : ''
  end

  def link_to_delete(obj)
    obj ? link_to(icon(:delete, t(:Delete)), obj, :confirm => t(:Delete_Confirm), :method => :delete) : ''
  end

  def link_to_edit(ops={})
    ops ? link_to(icon(:edit, t(:Edit)), ops) : ''
  end

  def link_to_show(ops={})
    ops ? link_to(icon(:show, t(:Show)), ops) : ''
  end

  def link_to_show_edit_delete(obj, edit_obj_path)
    (obj ? link_to_show(obj) : '') + (edit_obj_path ? link_to_edit(edit_obj_path) : '') + (obj ? link_to_delete(obj) : '')
  end

  ### 

end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>

  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %><%= t(:error_explanation_header) %></h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:Name) %><br/>
    <%= f.text_field :name_in_en %>
  </div>

  <div class="field">
    <%= f.label t(:Width) %><br/>
    <%= f.text_field :width %>
  </div>

  <div class="field">
    <%= f.label t(:Height) %><br/>
    <%= f.text_field :height %>
  </div>

  <div class="field">
    <%= f.label t(:Source_URL) %><br/>
    <%= f.text_field :src %>
  </div>

  <div class="field">
    <%= f.label t(:Long_Desc_URL) %><br/>
    <%= f.text_field :longdesc %>
  </div>

  <div class="field">
    <%= f.label t(:Path) %><br/>
    <%= f.text_field :path %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/images/edit.html.erb
<%= begin_view_edit(:Image) %>
<%= render 'form' %>
<%= end_view_edit(images_path,@image) %>

app/views/images/index.html.erb
<%= begin_view_index(:Images) %>

<table class="datatable">

  <thead>
    <tr>
      <th></th>
      <th><%= t(:Name) %></th>
      <th><%= t(:Width) %></th>
      <th><%= t(:Height) %></th>
      <th><%= t(:Source_URL) %></th>
      <th><%= t(:Long_Desc_URL) %></th>
      <th><%= t(:Path) %></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
    <tr>
      <td><%= link_to_show_edit_delete(image,edit_image_path(image)) %></td>
      <td><%= image.name %></td> 
      <td><%= image.height %></td> 
      <td><%= image.width %></td> 
      <td><%= image.src %></td> 
      <td><%= image.longdesc %></td> 
      <td><%= image.path %></td> 
    </tr>
    <% end %>
  </tbody>

  <tfoot></tfoot>

</table>

<%= end_view_index(new_image_path) %>

app/views/images/new.html.erb
<%= begin_view_new(:Image) %>
<%= render 'form' %>
<%= end_view_new(images_path) %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<%= begin_view_show(:Image) %>

<%= h3(:Name) %>
<%= @image.name %>

<%= h3(:Width) %>
<%= @image.width %>

<%= h3(:Height) %>
<%= @image.height %>

<%= h3(:Source_URL) %>
<%= @image.src %>

<%= h3(:Long_Desc_URL) %>
<%= @image.longdesc %>

<%= h3(:Path) %>
<%= @image.path %>

<%= end_view_show(images_path,edit_image_path(@image)) %>

app/views/items/_etsy_listing.html.erb
<div class="etsy_listing">
<a href="<%= item.etsy_listing.url %>" title="<%= item.name %> - <%= item.category %> - <%= item.tags %>">view on etsy</a></h3>
</div>

app/views/items/_form.html.erb
<% size_short = 5 %>

<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %><%= t(:error_explanation_header) %></h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:Name) %><br/>
    <%= f.text_field :name_in_en %>
  </div>

  <div class="field">
    <%= f.label t(:Description) %><br/>
    <%= f.text_area :description_in_en %>
  </div>

  <div class="field">
    <%= f.label t(:Price) %><br/>
    <%= f.text_field :price_in_usd, :size => size_short %> <%= t(:USD) %>
  </div>

  <div class="field">
    <%= f.label t(:Height) %><br/>
    <%= f.text_field :height, :size => size_short %> <%= t(:Meters) %>
  </div>

  <div class="field">
    <%= f.label t(:Width) %><br/>
    <%= f.text_field :width, :size => size_short %> <%= t(:Meters) %>
  </div>

  <div class="field">
    <%= f.label t(:Length) %><br/>
    <%= f.text_field :length, :size => size_short %> <%= t(:Meters) %>
  </div>

  <div class="field">
    <%= f.label t(:Weight) %><br/>
    <%= f.text_field :mass, :size => size_short %> <%= t(:Grams) %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/items/_paypal_listing.html.erb
<div class="paypal_listing">
<form class="buy" action="https://www.paypal.com/cgi-bin/webscr" method="post"/>
<input type="hidden" name="cmd" value="_s-xclick"/>
<input type="hidden" name="hosted_button_id" value="<%= item.paypal_listing.hosted_button.code %>"/>
<input class="buy" type="submit" value="Buy"/>
</form>
</div>

app/views/items/edit.html.erb
<%= begin_view_edit(:Item) %>
<%= render 'form' %>
<%= end_view_edit(items_path,@item) %>

app/views/items/index.html.erb
<%= begin_view_index(:Items) %>

<table class="datatable">
  <thead>
    <tr>
      <th></th>
      <th><%= t(:Name) %></th>
      <th><%= t(:Price) %></th>
      <th><%= t(:Length) %></th>
      <th><%= t(:Width) %></th>
      <th><%= t(:Height) %></th>
      <th><%= t(:Volume) %></th>
      <th><%= t(:Weight) %></th>
    <th><%= t(:Description) %></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
    <tr>
      <td><%= link_to_show_edit_delete(item,edit_item_path(item)) %></td>
      <td><%= item.name %></td>
      <td><%= item.price %></td>
      <td><%= item.length %></td>
      <td><%= item.width %></td>
      <td><%= item.height %></td>
      <td><%= item.volume %></td>
      <td><%= item.weight %></td>
      <td><%= item.description[0,30] %></td>
    </tr>
    <% end %>
  </tbody>

  <tfoot></tfoot>

</table>

<%= end_view_index(new_item_path) %>

app/views/items/new.html.erb
<%= begin_view_new(:Item) %>
<%= render 'form' %>
<%= end_view_new(items_path) %>

app/views/items/show.html.erb
<% item || = @item %>
<p id="notice"><%= notice %></p>

<%= begin_view_show(:Item) %>

<div class="views item show">

<div class="name">
<h1><%= item.name %></h1>
</div>

<div class="category">
<h2><%= item.category %></h2>
</div>

<div class="tags">
<h3><%= item.tags %></h3>
</div>

<% if item.paypal_listing %>
<%= render 'paypal_listing' %>
<% end %>

<div class="description">
<%= item.description %>
</div>

<div class="price">
<%= item.price %> <%= t(:USD) %>
</div>

<% if item.etsy_listing %>
<%= render 'etsy_listing' %>
<% end %>

<div class="shipping">
<%= item.shipping || item.shop.shipping %>
</div>

<div class="dimensions">
<ul>
<li><% if item.weight %>Weight: <%= item.weight %> <%= t(:Grams)  %><% end %>
<li><% if item.length %>Length: <%= item.length %> <%= t(:Meters) %><% end %>
<li><% if item.width  %>Width:  <%= item.width  %> <%= t(:Meters) %><% end %>
<li><% if item.height %>Height: <%= item.height %> <%= t(:Meters) %><% end %>
<li><% if item.volume %>Volume: <%= item.volume %> <%= t(:Meters) %><% end %>
</ul>
</div>

</div>
<%= end_view_show(items_path, edit_item_path(item)) %>

app/views/shopkeepers/_form.html.erb
<%= form_for(@shopkeeper) do |f| %>
  <% if @shopkeeper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shopkeeper.errors.count, "error") %><%= t(:error_explanation_header) %></h2>

      <ul>
      <% @shopkeeper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">  
    <%= f.label "#{t(:Shop)} #{t(:Id)}" %><br/> 
    <%= f.text_field :shop_id %>

  <div class="field">  
    <%= f.label "#{t(:User)} #{t(:Id)}" %><br/> 
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shopkeepers/edit.html.erb
<%= begin_view_edit(:Shopkeeper) %>
<%= render 'form' %>
<%= end_view_edit(shopkeepers_path,@shopkeeper) %>

app/views/shopkeepers/index.html.erb
<%= begin_view_index(:Shopkeepers) %>

<table class="datatable">
  <thead>
    <tr>
      <th></th>
      <th><%= t(:Shop) %> <%= t(:Id) %></th>
      <th><%= t(:Shop) %> <%= t(:Name) %></th>
      <th><%= t(:User) %> <%= t(:Id) %></th>
      <th><%= t(:User) %> <%= t(:Name) %></th>
    </tr>
  </thead>

  <tbody>
    <% @shopkeepers.each do |shopkeeper| %>
    <tr>
      <td><%= link_to_show_edit_delete(shopkeeper, edit_shopkeeper_path(shopkeeper)) %></td>
      <td><%= shopkeeper.shop.id %></td>
      <td><%= shopkeeper.shop.name %></td>
      <td><%= shopkeeper.user.id %></td>
      <td><%= shopkeeper.user.name %></td>
    </tr>
    <% end %>
  </tbody>

  <tfoot></tfoot>

</table>

<%= end_view_index(new_shopkeeper_path) %>

app/views/shopkeepers/new.html.erb
<%= begin_view_new(:Shopkeeper) %>
<%= render 'form' %>
<%= end_view_new(shopkeepers_path) %>

app/views/shopkeepers/show.html.erb
<p id="notice"><%= notice %></p>

<%= begin_view_show(:Shopkeeper) %>

<%= h3(:Shop) %>
<%= @shopkeeper.shop.id %> <%= @shopkeeper.shop.name %>

<%= h3(:User) %>
<%= @shopkeeper.user.id %> <%= @shopkeeper.user.name %>

<%= end_view_show(shopkeepers_path, edit_shopkeeper_path(@shopkeeper)) %>

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %><%= t(:error_explanation_header) %></h2>

      <ul>
      <% @shop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:Name) %><br/>
    <%= f.text_field :name_in_en %>
  </div>

  <div class="field">
    <%= f.label t(:Description) %><br/>
    <%= f.text_area :description_in_en %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/shops/edit.html.erb
<%= begin_view_edit(:Shop) %>
<%= render 'form' %>
<%= end_view_edit(shops_path,@shop) %>

app/views/shops/index.html.erb
<%= begin_view_index(:Shops) %>

<table class="datatable">
  <thead>
    <tr>
      <th></th>
      <th><%= t(:Name) %></th>
      <th><%= t(:Description) %></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
    <tr>
      <td><%= link_to_show_edit_delete(shop,edit_shop_path(shop)) %></td>
      <td><%= shop.name %></td>
      <td><%= shop.description[0,30] %></td>
    </tr>
    <% end %>
  </tbody>

  <tfoot></tfoot>

</table>

<%= end_view_index(new_shop_path) %>

app/views/shops/new.html.erb
<%= begin_view_new(:Shop) %>
<%= render 'form' %>
<%= end_view_new(shops_path) %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<%= begin_view_show(:Shop) %>

<%= h3(:Name) %>
<%= @shop.name %>

<%= h3(:Description) %>
<%= @shop.description %>

<%= end_view_show(shops_path,edit_shop_path(@shop)) %>

app/views/users/_form.html.erb
<% size_short = 5 %>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %><%= t(:error_explanation_header) %></h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:Name) %><br/>
    <%= f.text_field :name_in_en %>
  </div>

  <div class="field">
    <%= f.label t(:Description) %><br/>
    <%= f.text_field :description_in_en %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= begin_view_edit(:User) %>
<%= render 'form' %>
<%= end_view_edit(users_path,@user) %>

app/views/users/index.html.erb
<%= begin_view_index(:Users) %>

<table class="datatable">
  <thead>
    <tr>
      <th></th>
      <th><%= t(:Name) %></th>
      <th><%= t(:Description) %></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to_show_edit_delete(user,edit_user_path(user)) %></td>
      <td><%= user.name %></td> 
      <td><%= user.description[0,30] %></td> 
    </tr>
    <% end %>
  </tbody>

  <tfoot></tfoot>

</table>

<%= end_view_index(new_user_path) %>

app/views/users/new.html.erb
<%= begin_view_new(:User) %>
<%= render 'form' %>
<%= end_view_new(users_path) %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= begin_view_show(:User) %>

<%= h3(:Name) %>
<%= @user.name %>

<%= h3(:Description) %>
<%= @user.description %>

<%= end_view_show(users_path,edit_user_path(@user)) %>